<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_26_Pandas Analysis.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [2]:
# !pip install -U datasets
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

---

## 🟩 Calculate Mean Salary (1.26.1)

In [3]:
df['salary_year_avg'].mean()

np.float64(123286.27407182401)

---

## 🟩 Calculate Median Salary (1.26.2)

In [4]:
df['salary_year_avg'].median()

115000.0

---

## 🟨 Average Hourly Salary by Job Title (1.26.3)

In [5]:
df.groupby('job_title_short')['salary_hour_avg'].mean()

job_title_short
Business Analyst             42.723415
Cloud Engineer               45.560715
Data Analyst                 38.106918
Data Engineer                57.196998
Data Scientist               49.361403
Machine Learning Engineer    48.477935
Senior Data Analyst          47.661218
Senior Data Engineer         62.848496
Senior Data Scientist        54.105631
Software Engineer            46.452019
Name: salary_hour_avg, dtype: float64

---

## 🟨 Job with Lowest Salary (1.26.4)

In [7]:
min_sal = df['salary_hour_avg'].idxmin()

---

In [11]:
df.iloc[min_sal][['job_title_short', 'salary_hour_avg']]

job_title_short    Data Scientist
salary_hour_avg               8.0
Name: 88185, dtype: object

## 🟨 Job Count by Country (1.26.5)

In [14]:
df.groupby('job_country').size()

job_country
Afghanistan      16
Albania         119
Algeria         111
Angola           11
Argentina      8736
               ...
Venezuela        69
Vietnam        2414
Yemen            10
Zambia          104
Zimbabwe         81
Length: 160, dtype: int64

---